export enum STATES {
  SHOW_EMAIL = 'SHOW_EMAIL',
  SEND_EMAIL = 'SEND_EMAIL',
  INFO_EMAIL = 'INFO_EMAIL',
  SHOW_CODE_CONFIRM = 'SHOW_CODE_CONFIRM',
}

export enum EVENTS {
  COLLECT_EMAIL = 'COLLECT_EMAIL',
  BACK_TO_EMAIL = 'BACK_TO_EMAIL',
  SEND_TO_CODE = 'SEND_TO_CODE',
}

export enum SERVICES {
  SERVICE_SEND_EMAIL = 'SERVICE_SEND_EMAIL',
} 

export enum ACTIONS {
  TOGGLE_LOADING = 'TOGGLE_LOADING',
}