export enum STATES {
  SHOW_EMAIL = 'SHOW_EMAIL',
  SHOW_PASSWORD = 'SHOW_PASSWORD',
  SEND_EMAIL = 'SEND_EMAIL',
  INFO_EMAIL = 'INFO_EMAIL',
  SHOW_CODE_CONFIRM = 'SHOW_CODE_CONFIRM',
  VALIDATE_CODE = 'VALIDATE_CODE',
  CODE_IS_VALID_GATEWAY = 'CODE_IS_VALID_GATEWAY',
  SAVE_PASSWORD = 'SAVE_PASSWORD',
  SUCCESS = 'SUCCESS',
}

export enum EVENTS {
  COLLECT_EMAIL = 'COLLECT_EMAIL',
  BACK_TO_EMAIL = 'BACK_TO_EMAIL',
  SEND_TO_CODE = 'SEND_TO_CODE',
  COLLECT_CODE = 'COLLECT_CODE',
  COLLECT_PASSWORD = 'COLLECT_PASSWORD',
}

export enum SERVICES {
  SERVICE_SEND_EMAIL = 'SERVICE_SEND_EMAIL',
  SERVICE_VALIDATE_CODE = 'SERVICE_VALIDATE_CODE',
  SERVICE_VALIDATE_PASSWORD ='SERVICE_VALIDATE_PASSWORD',
} 

export enum ACTIONS {
  TOGGLE_LOADING = 'TOGGLE_LOADING',
}